name: Repeat-Check Release

on:
  push:
    branches: [ master, release/0.0.1 ]

jobs:
  build:
    name: Create Release and Tag
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: ./gradlew repeat-check:build

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: 'MMMM DD, YYYY'

      - name: Set version lib into VERSION_NAME variable
        run: |
          VERSION_NAME=$(./gradlew -q repeat-check:versionTxt)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        run: ./gradlew repeat-check:changeLogUpdate

      - name: Update README.md
        run: ./gradlew repeat-check:replaceInFile

      - name: Read Release Note
        id: release_note
        uses: juliangruber/read-file-action@v1
        with:
          path: ./repeat-check/release_note.txt

      - name: Get the version
        id: get_version
        run: echo "version=$(cat ./repeat-check/version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: Release ${{ env.version }}
          body: |
            ## Release ${{ env.version }} - ${{ steps.current-time.outputs.formattedTime }}
            ${{ steps.release_note.outputs.content }}
          draft: false
          prerelease: false

      - name: Prepare environment for signing
        run: |
          echo '${{ secrets.SIGNING_SECRET_KEY_RING_FILE_CONTENT }}' | base64 -d > ${SIGNING_SECRET_KEY_RING_FILE}
        env:
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}

      - name: Release build
        run: ./gradlew repeat-check:assemble

      - name: Generate source jar and documentation
        run: ./gradlew androidSourcesJar javadocJar

      - name: Publish to MavenCentral
        run: ./gradlew repeat-check:publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}

      - name: Commit and push changes
        run: ./gradlew addCommitPush
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
