name: Unit Tests
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!release_note.txt'

  pull_request:
    branches: [ develop ]

jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build test artifact
        run: ./gradlew repeat-check:build
      - name: Unit Tests
        run: ./gradlew repeat-check:test