name: Unit Tests
on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - 'release_note.txt'
  pull_request:
    branches: [ develop ]

jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '1.8'
      - name: Cache Gradle Wrapper and Caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Creating local.properties
        run: touch local.properties
      - name: Build test artifact
        run: ./gradlew repeat-check:build
      - name: Unit Tests
        run: ./gradlew repeat-check:test
